# username and password have intentonally been left blank
# Heroku would fill both of these in when we deploy and they
# are not needed locally

development:
  adapter: postgresql
  database: dev_codedoor
  pool: 5
  timeout: 5000
  username:
  password:

test:
  adapter: postgresql
  database: test_codedoor
  pool: 5
  timeout: 5000
  username:
  password:

production:
  adapter: postgresql
  database: prod_codedoor
  pool: 5
  timeout: 5000
  username:
  password:
